import { BrowserWindow, session } from 'electron'
import { writeFile, readFile, existsSync, mkdirSync } from 'fs'
import { join } from 'path'
import { app } from 'electron'
import log from 'electron-log'

export interface PlatformConfig {
  id: string
  name: string
  loginUrl: string
  /** Domain to capture cookies from after login */
  cookieDomain: string
  /** How to detect successful login (URL pattern or page title) */
  loginCheck: { type: 'url'; pattern: string } | { type: 'cookie'; name: string }
}

export const PLATFORMS: PlatformConfig[] = [
  {
    id: 'bilibili',
    name: 'B站',
    loginUrl: 'https://passport.bilibili.com/login',
    cookieDomain: '.bilibili.com',
    loginCheck: { type: 'url', pattern: 'bilibili.com' }
  },
  {
    id: 'youtube',
    name: 'YouTube',
    loginUrl: 'https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fwww.youtube.com',
    cookieDomain: '.youtube.com',
    loginCheck: { type: 'cookie', name: 'SID' }
  },
  {
    id: 'youku',
    name: '优酷',
    loginUrl: 'https://account.youku.com/',
    cookieDomain: '.youku.com',
    loginCheck: { type: 'cookie', name: 'yktk' }
  },
  {
    id: 'iqiyi',
    name: '爱奇艺',
    loginUrl: 'https://passport.iqiyi.com/pages/pc/login',
    cookieDomain: '.iqiyi.com',
    loginCheck: { type: 'cookie', name: 'P00001' }
  },
  {
    id: 'douyin',
    name: '抖音',
    loginUrl: 'https://www.douyin.com',
    cookieDomain: '.douyin.com',
    loginCheck: { type: 'cookie', name: 'sessionid' }
  }
]

function getCookiesDir(): string {
  const dir = join(app.getPath('userData'), 'cookies')
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  return dir
}

function getCookiePath(platformId: string): string {
  return join(getCookiesDir(), `${platformId}.txt`)
}

/**
 * Convert Electron cookies to Netscape cookies.txt format (for yt-dlp)
 */
function cookiesToNetscape(cookies: Electron.Cookie[]): string {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by AI Interpreter']
  for (const c of cookies) {
    const domain = c.domain ? (c.domain.startsWith('.') ? c.domain : `.${c.domain}`) : ''
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const secure = c.secure ? 'TRUE' : 'FALSE'
    const expiry = c.expirationDate ? Math.floor(c.expirationDate).toString() : '0'
    lines.push(`${domain}\t${flag}\t${c.path}\t${secure}\t${expiry}\t${c.name}\t${c.value}`)
  }
  return lines.join('\n')
}

/**
 * Open a login window for the given platform.
 * Returns true if login succeeded (cookies captured).
 */
export async function openLoginWindow(platformId: string): Promise<{ success: boolean; error?: string }> {
  const platform = PLATFORMS.find((p) => p.id === platformId)
  if (!platform) return { success: false, error: `Unknown platform: ${platformId}` }

  return new Promise((resolve) => {
    const LOGIN_TIMEOUT = 5 * 60 * 1000 // 5 minutes
    const loginWindow = new BrowserWindow({
      width: 500,
      height: 700,
      title: `Login - ${platform.name}`,
      parent: BrowserWindow.getFocusedWindow() || undefined,
      modal: false,
      webPreferences: {
        session: session.fromPartition(`persist:login-${platformId}`)
      }
    })

    loginWindow.loadURL(platform.loginUrl)

    let resolved = false

    const timeout = setTimeout(() => {
      if (!resolved) {
        resolved = true
        resolve({ success: false, error: '登录超时，请重试' })
        try { loginWindow.destroy() } catch {}
      }
    }, LOGIN_TIMEOUT)

    const cleanup = () => {
      clearTimeout(timeout)
      if (!resolved) {
        resolved = true
        resolve({ success: false, error: 'Login window closed by user' })
      }
      try { loginWindow.destroy() } catch {}
    }

    loginWindow.on('closed', cleanup)

    // Check for login success
    const checkLogin = async () => {
      if (resolved) return

      try {
        const cookies = await loginWindow.webContents.session.cookies.get({
          domain: platform.cookieDomain
        })

        if (platform.loginCheck.type === 'cookie') {
          const found = cookies.some((c) => c.name === (platform.loginCheck as { type: 'cookie'; name: string }).name)
          if (found) {
            resolved = true
            clearTimeout(timeout)
            await saveCookies(platformId, cookies)
            log.info(`[Auth] ${platform.name} login successful, ${cookies.length} cookies saved`)
            loginWindow.close()
            resolve({ success: true })
            return
          }
        }
      } catch {}
    }

    // Monitor URL changes and page loads
    loginWindow.webContents.on('did-navigate', async () => {
      if (platform.loginCheck.type === 'url') {
        const url = loginWindow.webContents.getURL()
        if (url.includes(platform.loginCheck.pattern) && !url.includes('login') && !url.includes('passport')) {
          resolved = true
          clearTimeout(timeout)
          const cookies = await loginWindow.webContents.session.cookies.get({
            domain: platform.cookieDomain
          })
          await saveCookies(platformId, cookies)
          log.info(`[Auth] ${platform.name} login successful, ${cookies.length} cookies saved`)
          loginWindow.close()
          resolve({ success: true })
        }
      }
    })

    loginWindow.webContents.on('did-finish-load', checkLogin)

    // Periodic check for cookie-based detection
    if (platform.loginCheck.type === 'cookie') {
      const timer = setInterval(async () => {
        if (resolved || loginWindow.isDestroyed()) {
          clearInterval(timer)
          return
        }
        await checkLogin()
      }, 2000)
    }
  })
}

async function saveCookies(platformId: string, cookies: Electron.Cookie[]): Promise<void> {
  const path = getCookiePath(platformId)
  const content = cookiesToNetscape(cookies)
  return new Promise((resolve, reject) => {
    writeFile(path, content, 'utf-8', (err) => {
      if (err) reject(err)
      else resolve()
    })
  })
}

/**
 * Get saved cookies file path for a platform, or null if not logged in.
 */
export function getCookiesForPlatform(platformId: string): string | null {
  const path = getCookiePath(platformId)
  return existsSync(path) ? path : null
}

/**
 * Check which platforms have saved cookies.
 */
export function getLoggedInPlatforms(): string[] {
  return PLATFORMS
    .filter((p) => existsSync(getCookiePath(p.id)))
    .map((p) => p.id)
}

/**
 * Delete saved cookies for a platform (logout).
 */
export function clearPlatformCookies(platformId: string): void {
  const path = getCookiePath(platformId)
  if (existsSync(path)) {
    const fs = require('fs')
    fs.unlinkSync(path)
  }
  // Also clear the Electron session
  session.fromPartition(`persist:login-${platformId}`).clearStorageData()
}

/**
 * Detect platform from URL and return appropriate cookies path.
 */
export function detectPlatformCookies(url: string): string | null {
  for (const platform of PLATFORMS) {
    if (url.includes(platform.cookieDomain.replace('.', ''))) {
      return getCookiesForPlatform(platform.id)
    }
  }
  return null
}
